### ISSUE TITLE
MBAR import error

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pyfeat#20]
## ERROR: Failure: ImportError (cannot import name MBAR)

Traceback (most recent call last):
  File "/Users/chris/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/chris/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/chris/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/chris/git/pyfeat/pyfeat/api/**init**.py", line 1, in <module>
    from .api import wham
  File "/Users/chris/git/pyfeat/pyfeat/api/api.py", line 12, in <module>
    from ..estimator import WHAM, XTRAM, DTRAM, TRAM, MBAR
ImportError: cannot import name MBAR

**Comment by ppxasjsm** [comment]
ill check that
